name: inception

services:
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
    restart: always

  wordpress:
    build: ./wordpress
    ports:
      - "9000:9000"
    volumes:
      - ./data/wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    build: ./mariadb
    volumes:
      - ./data/mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network
    depends_on:
      - nginx

networks:
  inception_network:
    driver: bridge
