version: '3.8'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]  # Use $$ para escapar as variáveis
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/wp-admin/install.php || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  prometheus:
    build:
      context: ./bonus/prometheus  # Diretório do Dockerfile do Prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./bonus/prometheus/tools/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - inception  # Conectado à rede inception
      - monitoramento

  grafana:
    build:
      context: ./bonus/grafana  # Diretório do Dockerfile do Grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./bonus/grafana/tools/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - inception  # Conectado à rede inception
      - monitoramento
    depends_on:
      - prometheus

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/aqueiroz/inception/data/wordpress
      o: bind

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/aqueiroz/inception/data/mariadb
      o: bind

  grafana-storage:  # Volume para o Grafana
    driver: local

networks:
  inception:
    driver: bridge

  monitoramento:
    driver: bridge