name: "inception"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - ./web:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    restart: always
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=wordpress
      - DD_ENV=production
      - DD_TRACE_ENABLED=true 
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - inception
  datadog:
    container_name: datadog
    build: bonus/datadog
    environment:
      - DD_API_KEY=<sua_chave_de_api>
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true 
    ports:
      - 8125:8125/udp
      - 8126:8126
      - 8125:8125
    networks:
      - inception
    depends_on:
      - nginx
    restart: always

networks:
  inception: