global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scheme: https
    tls_config:
      cert_file: /etc/ssl/certs/nginx-selfsigned.crt
      key_file: /etc/ssl/private/nginx-selfsigned.key
      insecure_skip_verify: true

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:443']
    metrics_path: '/nginx_status'
    scheme: https
    tls_config:
      cert_file: /etc/ssl/certs/nginx-selfsigned.crt
      key_file: /etc/ssl/private/nginx-selfsigned.key
      insecure_skip_verify: true

  - job_name: 'wordpress'
    static_configs:
      - targets: ['wordpress:80']
    metrics_path: '/metrics'
    scheme: https
    tls_config:
      cert_file: /etc/ssl/certs/nginx-selfsigned.crt
      key_file: /etc/ssl/private/nginx-selfsigned.key
      insecure_skip_verify: true

  - job_name: 'vault'
    static_configs:
      - targets: ['vault:8200']
    metrics_path: '/v1/sys/metrics'
    scheme: https
    tls_config:
      cert_file: /etc/ssl/certs/nginx-selfsigned.crt
      key_file: /etc/ssl/private/nginx-selfsigned.key
      insecure_skip_verify: true

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scheme: https
    tls_config:
      cert_file: /etc/ssl/certs/nginx-selfsigned.crt
      key_file: /etc/ssl/private/nginx-selfsigned.key
      insecure_skip_verify: true